# Generated by Django 5.0.3 on 2024-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
